# Header

menu:
  å‰ç«¯: /tags/å‰ç«¯
  åç«¯: /tags/åç«¯
  å‘¨è¾¹æŠ€æœ¯: /tags/å‘¨è¾¹æŠ€æœ¯

# SubNav
subnav:
  github: https://github.com/Aric-sky
  #zhihu: https://zhihu.com/people/CrazyMilk
  #psn: "#"
  #zhihu: "#"
  #douban: "#"
  segmentfault: https://segmentfault.com/u/wangyuanqi
  #bilibili: "#"
  #acfun: "#"
  mail: mailto://wangyuanqi518@163.com
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /

# Content
excerpt_link: 'more'
show_all_link: 'å±•å¼€å…¨æ–‡'
fancybox: true
mathjax: false

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
reward_wording: 'å¸®åŠ©æ¥¼ä¸»è¿å¨¶ç™½å¯Œç¾'
alipay: /assets/images/pay/alipay.jpg
weixin: /assets/images/pay/weixin.jpg

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 1
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/images/favicon/favicon.ico

#ä½ çš„å¤´åƒurl
avatar: /assets/images/avatar/avatar1.png

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

mobile:
  social: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqus ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#è¯·å‚è€ƒwikiï¼š

#1ã€å¤šè¯´
#duoshuo: "litten-hexo"

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3ã€ç•…è¨€
#  changyan_appid: 'cytUva5N5'
#  changyan_conf: 'prod_407744d24cde05583eb5b17e5ec9f944'

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
# disqus: false

#5ã€å‹è¨€
# uyan: '2157287'

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æœç´¢æ–‡ç«  ğŸ”'
  # friends: 'å‹é“¾'
  # aboutme: 'å…³äºæˆ‘'

friends:
  Aric-Factory: wangyuanqi.leanapp.cn


aboutme: I Like Codding Bug !

#leancloud
leancloud_visitors:
  enable: true
  app_id: MaWKKnTCPQkl8zu6Ao9qij6A-gzGzoHsz
  app_key: qEIdCWy73vw1uzMzDC8F9jIt

#æ·»åŠ ä¸€ä¸‹jsæ’ä»¶çš„ CDNåœ°å€
js_cdn:
  jquery: https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js
  av : //cdn1.lncld.net/static/js/2.5.0/av-min.js
